name: WebMethods Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target Environment"
        required: true
        type: choice
        options:
          - DEV
          - QA
          - UAT
          - PROD

      version:
        description: "Artifact Version"
        required: true
        type: string

      deploy_tn:
        description: "Deploy Trading Networks?"
        required: true
        type: boolean
        default: false

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Display Inputs
        shell: powershell
        run: |
          Write-Host "Environment : ${{ inputs.environment }}"
          Write-Host "Version     : ${{ inputs.version }}"
          Write-Host "Deploy TN   : ${{ inputs.deploy_tn }}"
